title: Humble Learning
description: >- # this means to ignore newlines until "baseurl:"
  I write about my never-ending learning path.
baseurl: ""
url: "https://andreashassing.github.io"
twitter_username: AndreasHassing
github_username:  AndreasHassing

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
